debug: false
management.endpoint.web.exposure.include: "*"

logging:
  level:
    org.dry: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

mybatis:
  type-aliases-package: org.dry.entity
  mapper-locations: classpath:mappers/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drytable
    username: "un"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: NEVER
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
